---
language: php

php:
- '5.3'

branches:
  only:
    - master

before_script:
- mysql -e 'create database irex_test;'
- composer install
- php artisan migrate:refresh --seed --env='testing'

after_script:
- mysql -e 'drop database irex_test;'

notifications:
  email:
    - memborsky@gmail.com