---
language: php

php:
  - '5.3'
  - '5.4'

branches:
  only:
    - master

before_script:
  - mysql -e 'create database irex_test;'
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --prefer-source --dev
  - php artisan migrate --env='testing'
  - php artisan db:seed --env='testing'

notifications:
  email:
    - memborsky@gmail.com
  on_success: never
  on_failure: always